# Render Blueprint Configuration
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: pym-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pym_be.wsgi:application
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pym-database
          property: connectionString

databases:
  - name: pym-database
    plan: free

