apiVersion: v1
kind: ConfigMap
metadata:
  name: pym-config
  namespace: pour-your-mind
data:
  DEBUG: "0"
  POSTGRES_DB: "pym_db"
  POSTGRES_USER: "pym_user"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"

