apiVersion: v1
kind: Secret
metadata:
  name: pym-secrets
  namespace: pour-your-mind
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  POSTGRES_PASSWORD: cHltX3Bhc3N3b3Jk # pym_password
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWtleQ== # django-insecure-key

